DROP DATABASE IF EXISTS trackfy_db;
CREATE DATABASE IF NOT EXISTS trackfy_db CHARSET utf8mb4 ;
USE trackfy_db;

CREATE TABLE IF NOT EXISTS users(
	id_user BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	username VARCHAR(255) NOT NULL UNIQUE,
    displayname VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    foto VARCHAR(255) DEFAULT 'default-user.png',
    bio TEXT,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS albums(
	id_album BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255),
	artist VARCHAR(255),
	cover TEXT,
	release_year INT,
	total_duration INT,

	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tracks(
	id_track BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	album_id BIGINT UNSIGNED,

	title VARCHAR(255),
	artist VARCHAR(255),
	cover_url TEXT,
	release_year INT,
	duration_seconds INT,

	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (album_id) REFERENCES albums(id_album)
);

CREATE TABLE IF NOT EXISTS reviews(
	id_review BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    
	user_id BIGINT UNSIGNED NOT NULL,
	track_id BIGINT UNSIGNED NOT NULL,
    
	nota TINYINT UNSIGNED CHECK (nota BETWEEN 1 AND 10),
	descricao TEXT,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id_user),
    FOREIGN KEY (track_id) REFERENCES tracks(id_track),
    UNIQUE(user_id, track_id)
);

CREATE TABLE IF NOT EXISTS saved_tracks(
	id_saved_tracks BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	track_id BIGINT UNSIGNED NOT NULL,
	user_id BIGINT UNSIGNED NOT NULL,

	saved_at DATETIME DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users(id_user),
	FOREIGN KEY (track_id) REFERENCES tracks(id_track),
	UNIQUE(user_id, track_id)
);

CREATE TABLE IF NOT EXISTS favorite_albums(
	id_favorite_albuns BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	album_id BIGINT UNSIGNED NOT NULL,
	user_id BIGINT UNSIGNED NOT NULL,

	saved_at DATETIME DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users(id_user),
	FOREIGN KEY (album_id) REFERENCES albums(id_album),
	UNIQUE(user_id, album_id)
);