CREATE DATABASE IF NOT EXISTS trackfy_db CHARSET utf8mb4 ;
USE trackfy_db;

CREATE TABLE IF NOT EXISTS users(
	id_user BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    foto VARCHAR(255) DEFAULT 'default-user.png',
    bio TEXT ,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews(
	id_review BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    
	user_id BIGINT UNSIGNED NOT NULL,
	music_api_id VARCHAR(255) NOT NULL,
    
	nota TINYINT UNSIGNED,
	descricao TEXT,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id_user),
    UNIQUE(user_id, music_api_id)
);

CREATE TABLE IF NOT EXISTS tracks(
	id_track BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	api_id VARCHAR(255) UNIQUE,
	title VARCHAR(255),
	artist VARCHAR(255),
	album VARCHAR(255),
	cover_url TEXT
);

CREATE TABLE saved_tracks(
	id_saved BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT UNSIGNED,
	music_api_id VARCHAR(255),

	FOREIGN KEY (user_id) REFERENCES users(id_user)
);